use anyhow::Result;
use quinn::{ClientConfig, Connection, SendStream, TransportConfig, VarInt};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, net::SocketAddr, sync::Arc, time::Duration};
use tokio::sync::{Mutex, mpsc};

use crate::{core::Event, logger, lsp::Position};

/// The packet we serialize and send over the QUIC stream.
#[derive(Serialize, Deserialize, Debug, Clone)]
enum WireMessage {
    Patch {
        uri: String,
        data: Vec<u8>,
    },

    Cursor {
        uri: String,
        position: (usize, usize),
    },

    /// Peer -> Host
    RequestFullSync,

    /// Host -> Peer
    FullSyncResponse {
        files: Vec<(String, Vec<u8>)>,
    },
}

#[derive(Debug)]
pub enum NetworkCommand {
    BroadcastCursor {
        uri: String,
        position: (usize, usize),
    },
    BroadcastPatch {
        uri: String,
        patch: Vec<u8>,
    },
    SendFullSyncResponse {
        files: Vec<(String, Vec<u8>)>,
    },
}

#[derive(Serialize, Deserialize, Debug, Clone)]
enum ControlMessage {
    InitSession { key: String },
    SessionCreated { status: String, name: String },
    JoinSession { name: String, key: String },
    SessionJoined { status: String },
    InitPeer { agent_id: String },
}

/// Connects to the given relay address and returns the send and recv streams.
///
/// # Arguments
///
/// * `relay_addr` - The address of the relay server to connect to
///
/// # Errors
///
/// Errors if:
///
/// * The local endpoint couldn't be initialized
/// * If the connection to the relay fails
pub async fn connect(
    relay_addr: SocketAddr,
) -> Result<quinn::Connection, Box<dyn std::error::Error>> {
    // Setup connection
    let mut endpoint = quinn::Endpoint::client("0.0.0.0:0".parse()?)?;
    let cfg = configure_client("");
    endpoint.set_default_client_config(cfg);

    let conn = endpoint.connect(relay_addr, "relay")?.await?;
    Ok(conn)
}

/// Controls the entire peer logic, including setup, sending and receiving data.
///
/// # Arguments
///
/// * `session_key` - The password of the session, specified by hosting peer
/// * `session_name` - The session name, generated by the relay server. Retrieve from hosting peer
/// * `core_tx` - The connection from network to core used for sending incoming events inwards to
///   compute
/// * `net_rx` - Outgoing traffic, computed patches coming from localhost
/// * `conn` - The configured connection to the relay server
///
/// # Panics
///
/// Panics if:
///
/// * A new peer attempts to connect but fails
/// * A new peer connects and opens streams, but the first message is no init
pub async fn run_peer(
    session_key: String,
    session_name: Option<String>,
    agent_id: String,
    core_tx: mpsc::Sender<Event>,
    mut net_rx: mpsc::Receiver<NetworkCommand>,
    conn: Connection,
) -> anyhow::Result<()> {
    let (mut send, mut recv) = conn.open_bi().await?;
    let mut is_host = false;
    if let Some(name) = session_name {
        join_session(&mut send, &mut recv, name, session_key).await?;
    } else {
        is_host = true;
        init_session(&mut send, &mut recv, session_key).await?;
    };

    // agent_id -> send to peer stream
    let peers: Arc<Mutex<HashMap<String, SendStream>>> = Arc::new(Mutex::new(HashMap::new()));
    let core_tx_ref = core_tx.clone();

    // Loop for accepting incoming peer stream requests in the relay's connection
    let peers_accept = Arc::clone(&peers);
    tokio::spawn(async move {
        loop {
            let new_peer = conn.accept_bi().await;
            match new_peer {
                Ok((mut send, mut recv)) => {
                    let init_msg = ControlMessage::InitPeer {
                        agent_id: agent_id.clone(),
                    };
                    send_framed(&mut send, &init_msg).await.expect("Couldn't send verify message");

                    let mut buf = vec![0u8; 1024];
                    let n = recv.read(&mut buf).await.unwrap().unwrap_or(0);

                    let msg: ControlMessage = serde_json::from_slice(&buf[..n])
                        .expect("Unable to deserialize incoming message");
                    if let ControlMessage::InitPeer { agent_id } = msg {
                        let mut p = peers_accept.lock().await;
                        p.insert(agent_id.clone(), send);
                        // Run receiving map for each peer in a separate thread
                        tokio::spawn(recv_loop(recv, core_tx_ref.clone(), is_host));
                    } else {
                        panic!("Invalid setup msg received, expected Init, got {:?}", msg);
                    }
                }
                Err(e) => {
                    panic!("{}", e);
                }
            }
        }
    });

    // Plain outbound traffic
    let peers_out = Arc::clone(&peers);
    tokio::spawn(async move {
        while let Some(cmd) = net_rx.recv().await {
            let wire_msg = match cmd {
                NetworkCommand::BroadcastCursor { uri, position } => {
                    WireMessage::Cursor { uri, position }
                }
                NetworkCommand::BroadcastPatch { uri, patch } => {
                    WireMessage::Patch { uri, data: patch }
                }
                NetworkCommand::SendFullSyncResponse { files } => {
                    WireMessage::FullSyncResponse { files }
                }
            };
            let mut p = peers_out.lock().await;
            broadcast(&mut p, wire_msg).await;
        }
    });

    // Cleanup
    let _ = core_tx.send(Event::Shutdown).await;
    Ok(())
}

/// Initializes a new session on the remote relay server
///
/// # Arguments
///
/// * `send` - The outgoing control stream to the relay server
/// * `recv` - The incoming control stream from the relay server
/// * `session_key` - The desired password for the session
async fn init_session(
    send: &mut quinn::SendStream,
    recv: &mut quinn::RecvStream,
    session_key: String,
) -> anyhow::Result<()> {
    let msg = ControlMessage::InitSession { key: session_key };

    let response = init(send, recv, msg).await?;

    if let ControlMessage::SessionCreated { status, name } = response {
        if status.eq("ok") {
            eprintln!("Created session - name: {}", name);
        } else {
            return Err(anyhow::Error::msg(
                "Unable to init session on relay server!",
            ));
        }
    } else {
        return Err(anyhow::Error::msg(
            "Invalid relay server response, check relay server logs for more information!",
        ));
    }

    Ok(())
}

/// Joins a session on the relay server
///
/// # Arguments
///
/// * `send` - The outgoing control stream to the relay server
/// * `recv` - The incoming control stream from the relay server
/// * `session_name` - The name of the session to join
/// * `session_key` - The password of the session to join
async fn join_session(
    send: &mut quinn::SendStream,
    recv: &mut quinn::RecvStream,
    session_name: String,
    session_key: String,
) -> anyhow::Result<()> {
    let msg = ControlMessage::JoinSession {
        name: session_name,
        key: session_key,
    };

    let response = init(send, recv, msg).await?;

    if let ControlMessage::SessionJoined { status } = response {
        if status.ne("ok") {
            return Err(anyhow::Error::msg(
                "Unable to init session on relay server!",
            ));
        }
    } else {
        return Err(anyhow::Error::msg(
            "Invalid relay server response, check relay server logs for more information!",
        ));
    }

    Ok(())
}

/// Sends the control message to the relay server and awaits (and returns) a response
///
/// # Arguments
///
/// * `send` - The outgoing stream to the relay server
/// * `recv` - The incoming stream from the relay server
/// * `msg` - The message to send through the control stream to the relay server
async fn init(
    send: &mut SendStream,
    recv: &mut quinn::RecvStream,
    msg: ControlMessage,
) -> anyhow::Result<ControlMessage> {
    send.write_all(&serde_json::to_vec(&msg)?).await?;
    send.finish()?;

    let mut buf = vec![0u8; 1024];
    let n = recv.read(&mut buf).await?.unwrap_or(0);

    Ok(serde_json::from_slice::<ControlMessage>(&buf[..n])?)
}

/// Runs the receiving loop (for each peer separately)
///
/// # Arguments
///
/// * `recv` - The incoming stream from the peer
/// * `core_tx` - The inward connection to the core for computing events
/// * `is_host` - Whether the local peer offers the project data for initial syncs
async fn recv_loop(mut recv: quinn::RecvStream, core_tx: mpsc::Sender<Event>, is_host: bool) {
    loop {
        match recv_framed(&mut recv).await {
            Ok(wire_msg) => {
                let core = core_tx.clone();
                let event: Event = match wire_msg {
                    WireMessage::Patch { uri, data } => {
                        logger::log(&format!(">> [Network] Received patch for {}", uri));
                        Event::RemotePatch { uri, patch: data }
                    }
                    WireMessage::Cursor { uri, position } => {
                        let (line, char) = position;
                        Event::RemoteCursorChange {
                            uri,
                            position: Position {
                                line,
                                character: char,
                            },
                        }
                    }
                    WireMessage::RequestFullSync => {
                        if is_host {
                            Event::PeerRequestedSync
                        } else {
                            Event::Ignoring
                        }
                    }
                    WireMessage::FullSyncResponse { files } => Event::RemoteFullSync { files },
                };

                // Local outgoing
                match core.send(event.clone()).await {
                    Ok(_) => println!("Sent patch to remote!"),
                    Err(e) => eprintln!("Couldn't send patch to remote: {}", e),
                }
            }
            Err(e) => {
                crate::logger::log(&format!(
                    "!! [Network] Read error (connection closed): {}",
                    e
                ));
                break;
            }
        }
    }
}

/// Broadcasts changes to all peers
///
/// # Arguments
///
/// * `peers` - The vec of peers to sync to
/// * `msg` - The msg to sync to all peers
async fn broadcast(peers: &mut HashMap<String, quinn::SendStream>, msg: WireMessage) {
    for (agent_id, send) in peers.iter_mut() {
        if let Err(e) = send_framed(send, &msg).await {
            logger::log(&format!(
                "!! [Network] Broadcast to {} failed: {}",
                agent_id, e
            ));
        }
    }
}

/// Sends a framed message to a stream. Framed in this case means prefixing the actual message with
/// a message length header.
///
/// # Arguments
///
/// * `send` - The send stream, to write the data to
/// * `msg` - The msg to send
///
/// # Errors
///
/// * If serializing the msg fails
/// * If writing to the stream fails, eg due to overful stream
async fn send_framed<T>(send: &mut quinn::SendStream, msg: T) -> Result<()>
where
    T: Sized + Serialize,
{
    let bytes = serde_json::to_vec(&msg)?;
    let len = bytes.len() as u32;

    send.write_all(&len.to_be_bytes()).await?;
    send.write_all(&bytes).await?;
    Ok(())
}

/// Helper function to receive framed messages produced by a remote's send_framed
///
/// # Arguments
///
/// * `recv` - The receiving stream
///
/// # Errors
///
/// * If reading into the buffer fails
/// * If the incoming message is too large (>100MB)
/// * If deserializing fails
async fn recv_framed(recv: &mut quinn::RecvStream) -> Result<WireMessage> {
    let mut len_buf = [0u8; 4];
    recv.read_exact(&mut len_buf).await?;
    let len = u32::from_be_bytes(len_buf) as usize;

    if len > 100 * 1024 * 1024 {
        return Err(anyhow::anyhow!("Message too large (100MB limit)"));
    }

    let mut buf = vec![0u8; len];
    recv.read_exact(&mut buf).await?;

    let msg = serde_json::from_slice(&buf)?;
    Ok(msg)
}

// =========================================================================
//  Configuration (TLS & QUIC)
// =========================================================================

fn make_transport_config() -> TransportConfig {
    let mut transport_config = TransportConfig::default();
    transport_config.max_concurrent_uni_streams(VarInt::from_u32(100));
    transport_config.keep_alive_interval(Some(Duration::from_secs(2)));
    transport_config.max_idle_timeout(Some(VarInt::from_u32(30_000).into()));
    transport_config
}

fn configure_client(token: &str) -> ClientConfig {
    // Use own verifier
    let verifier = crate::crypto::TokenVerifier::new(token);

    let mut crypto = rustls::ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(verifier)
        .with_no_client_auth();

    // ALPN has to match
    crypto.alpn_protocols = vec![b"justsync".to_vec()];

    let mut config = ClientConfig::new(Arc::new(
        quinn::crypto::rustls::QuicClientConfig::try_from(crypto).unwrap(),
    ));
    config.transport_config(Arc::new(make_transport_config()));
    config
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto;
    use tokio::sync::mpsc;

    #[test]
    fn test_wire_message_roundtrip() {
        let original = WireMessage::Patch {
            uri: "file:///test.rs".to_string(),
            data: vec![1, 2, 3, 4],
        };

        let encoded = serde_json::to_vec(&original).unwrap();
        let decoded: WireMessage = serde_json::from_slice(&encoded).unwrap();

        match decoded {
            WireMessage::Patch { uri, data } => {
                assert_eq!(uri, "file:///test.rs");
                assert_eq!(data, vec![1, 2, 3, 4]);
            }
            _ => panic!("Wrong variant"),
        }
    }

    #[tokio::test]
    async fn test_quic_integration() {
        // 1. Setup Crypto (Certs & Token)
        let _ = rustls::crypto::ring::default_provider().install_default();
        let (server_certs, server_key, token) = crypto::generate_cert_and_token();

        // 2. Setup Channels
        let (host_core_tx, mut host_core_rx) = mpsc::channel(10);
        let (host_net_tx, host_net_rx) = mpsc::channel(10);

        let (peer_core_tx, mut peer_core_rx) = mpsc::channel(10);
        let (_peer_net_tx, peer_net_rx) = mpsc::channel(10);

        // 3. Start Host
        // Port 0 lets the OS pick a random free port
        let certs_clone = server_certs.clone();
        let key_clone = server_key.clone_key();

        // We need to run the host in a way that we can extract the port.
        // But network::run() consumes the future.
        // We'll trust the "bind to port 0" logic inside `init_host` works,
        // but we need to know WHICH port it picked to tell the client.
        // Since `run` is opaque, we'll modify the test to use a fixed high port
        // to avoid race conditions, or we assume 50000+ range.
        let test_port = 54321;

        let host_handle = tokio::spawn(async move {
            run(
                "host".to_string(),
                None,
                test_port,
                host_core_tx,
                host_net_rx,
                "".to_string(), // Host ignores token string, generates its own or uses certs
                Some(certs_clone),
                Some(key_clone),
            )
            .await;
        });

        // Give host a moment to bind
        tokio::time::sleep(Duration::from_millis(200)).await;

        // 4. Start Peer
        let token_clone = token.clone();
        let peer_handle = tokio::spawn(async move {
            run(
                "peer".to_string(),
                Some("127.0.0.1".to_string()),
                test_port,
                peer_core_tx,
                peer_net_rx,
                token_clone,
                None,
                None,
            )
            .await;
        });

        // 5. Verification Steps

        // A. Peer connects -> Sends RequestFullSync (Startup logic)
        // B. Host should receive PeerRequestedSync
        match tokio::time::timeout(Duration::from_secs(2), host_core_rx.recv()).await {
            Ok(Some(Event::PeerRequestedSync)) => {
                println!("Test: Host received sync request");
            }
            res => panic!("Host did not receive Sync Request: {:?}", res),
        }

        // C. Host Sends Response
        host_net_tx
            .send(NetworkCommand::SendFullSyncResponse {
                files: vec![("doc.txt".into(), vec![65, 66, 67])],
            })
            .await
            .unwrap();

        // D. Peer should receive RemoteFullSync
        match tokio::time::timeout(Duration::from_secs(2), peer_core_rx.recv()).await {
            Ok(Some(Event::RemoteFullSync { files })) => {
                assert_eq!(files[0].0, "doc.txt");
                assert_eq!(files[0].1, vec![65, 66, 67]);
                println!("Test: Peer received full sync");
            }
            res => panic!("Peer did not receive Sync Response: {:?}", res),
        }

        // Cleanup
        host_handle.abort();
        peer_handle.abort();
    }
}
