// To regenerate protobuf golang code:
// protoc --go_out=. --go_opt=paths=source_relative snapshot/snapshot.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: snapshot/snapshot.proto

package snapshot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The top-level message for all websocket communication.
type WebsocketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*WebsocketMessage_FileDelta
	//	*WebsocketMessage_InitialFile
	//	*WebsocketMessage_StartSync
	//	*WebsocketMessage_EndSync
	Payload isWebsocketMessage_Payload `protobuf_oneof:"payload"`
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{0}
}

func (m *WebsocketMessage) GetPayload() isWebsocketMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *WebsocketMessage) GetFileDelta() *FileDelta {
	if x, ok := x.GetPayload().(*WebsocketMessage_FileDelta); ok {
		return x.FileDelta
	}
	return nil
}

func (x *WebsocketMessage) GetInitialFile() *InitialSyncFileWithPath {
	if x, ok := x.GetPayload().(*WebsocketMessage_InitialFile); ok {
		return x.InitialFile
	}
	return nil
}

func (x *WebsocketMessage) GetStartSync() *StartProjectSync {
	if x, ok := x.GetPayload().(*WebsocketMessage_StartSync); ok {
		return x.StartSync
	}
	return nil
}

func (x *WebsocketMessage) GetEndSync() *EndProjectSync {
	if x, ok := x.GetPayload().(*WebsocketMessage_EndSync); ok {
		return x.EndSync
	}
	return nil
}

type isWebsocketMessage_Payload interface {
	isWebsocketMessage_Payload()
}

type WebsocketMessage_FileDelta struct {
	// SERVER -> CLIENT: The primary message. Contains all the changes for a
	// single file.
	FileDelta *FileDelta `protobuf:"bytes,1,opt,name=file_delta,json=fileDelta,proto3,oneof"`
}

type WebsocketMessage_InitialFile struct {
	// SERVER -> CLIENT: Sends a file for initial project sync to the client
	InitialFile *InitialSyncFileWithPath `protobuf:"bytes,3,opt,name=initial_file,json=initialFile,proto3,oneof"`
}

type WebsocketMessage_StartSync struct {
	StartSync *StartProjectSync `protobuf:"bytes,4,opt,name=start_sync,json=startSync,proto3,oneof"`
}

type WebsocketMessage_EndSync struct {
	EndSync *EndProjectSync `protobuf:"bytes,5,opt,name=end_sync,json=endSync,proto3,oneof"`
}

func (*WebsocketMessage_FileDelta) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_InitialFile) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_StartSync) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_EndSync) isWebsocketMessage_Payload() {}

// A self-contained package describing all the changes for a single file
// needed to bring it from State N-1 to the newest State N.
type FileDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The relative path of the file that was modified.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The final BLAKE3 hash of the entire file after the delta is applied.
	// The client MUST use this to verify the patch was successful.
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// A list of chunks that are NEW to the file. Their content is included.
	AddedChunks []*AddedChunk `protobuf:"bytes,3,rep,name=added_chunks,json=addedChunks,proto3" json:"added_chunks,omitempty"`
	// A list of hashes for chunks that were REMOVED from the file.
	RemovedChunkHashes [][]byte `protobuf:"bytes,4,rep,name=removed_chunk_hashes,json=removedChunkHashes,proto3" json:"removed_chunk_hashes,omitempty"`
	// A list of chunks that were already in the file but MOVED to a new position.
	MovedChunks []*MovedChunk `protobuf:"bytes,5,rep,name=moved_chunks,json=movedChunks,proto3" json:"moved_chunks,omitempty"`
}

func (x *FileDelta) Reset() {
	*x = FileDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDelta) ProtoMessage() {}

func (x *FileDelta) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDelta.ProtoReflect.Descriptor instead.
func (*FileDelta) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *FileDelta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDelta) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *FileDelta) GetAddedChunks() []*AddedChunk {
	if x != nil {
		return x.AddedChunks
	}
	return nil
}

func (x *FileDelta) GetRemovedChunkHashes() [][]byte {
	if x != nil {
		return x.RemovedChunkHashes
	}
	return nil
}

func (x *FileDelta) GetMovedChunks() []*MovedChunk {
	if x != nil {
		return x.MovedChunks
	}
	return nil
}

// Carries the content and metadata for a new chunk.
type AddedChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checksum  []byte `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Content   []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	NewOffset int64  `protobuf:"varint,3,opt,name=new_offset,json=newOffset,proto3" json:"new_offset,omitempty"`
	Version   int64  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AddedChunk) Reset() {
	*x = AddedChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedChunk) ProtoMessage() {}

func (x *AddedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedChunk.ProtoReflect.Descriptor instead.
func (*AddedChunk) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *AddedChunk) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *AddedChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AddedChunk) GetNewOffset() int64 {
	if x != nil {
		return x.NewOffset
	}
	return 0
}

func (x *AddedChunk) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Describes the new position for an existing chunk.
type MovedChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checksum  []byte `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	NewOffset int64  `protobuf:"varint,2,opt,name=new_offset,json=newOffset,proto3" json:"new_offset,omitempty"`
	Version   int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *MovedChunk) Reset() {
	*x = MovedChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovedChunk) ProtoMessage() {}

func (x *MovedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovedChunk.ProtoReflect.Descriptor instead.
func (*MovedChunk) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *MovedChunk) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *MovedChunk) GetNewOffset() int64 {
	if x != nil {
		return x.NewOffset
	}
	return 0
}

func (x *MovedChunk) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StartProjectSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartProjectSync) Reset() {
	*x = StartProjectSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProjectSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProjectSync) ProtoMessage() {}

func (x *StartProjectSync) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProjectSync.ProtoReflect.Descriptor instead.
func (*StartProjectSync) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{4}
}

type EndProjectSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndProjectSync) Reset() {
	*x = EndProjectSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndProjectSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndProjectSync) ProtoMessage() {}

func (x *EndProjectSync) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndProjectSync.ProtoReflect.Descriptor instead.
func (*EndProjectSync) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{5}
}

type InitialSyncFileWithPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []byte           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	File *InitialSyncFile `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *InitialSyncFileWithPath) Reset() {
	*x = InitialSyncFileWithPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialSyncFileWithPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncFileWithPath) ProtoMessage() {}

func (x *InitialSyncFileWithPath) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncFileWithPath.ProtoReflect.Descriptor instead.
func (*InitialSyncFileWithPath) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *InitialSyncFileWithPath) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *InitialSyncFileWithPath) GetFile() *InitialSyncFile {
	if x != nil {
		return x.File
	}
	return nil
}

// A plain file used for storing rather than synchronizing
type InitialSyncFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file's checksum (a BLAKE3 generated hash of it's content)
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// A list of chunks representing this file's content
	Chunks []*InitialSyncChunk `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *InitialSyncFile) Reset() {
	*x = InitialSyncFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialSyncFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncFile) ProtoMessage() {}

func (x *InitialSyncFile) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncFile.ProtoReflect.Descriptor instead.
func (*InitialSyncFile) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *InitialSyncFile) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *InitialSyncFile) GetChunks() []*InitialSyncChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// A plain chunk used for storing rather than synchronizing
type InitialSyncChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The chunk's checksum (a BLAKE3 generated hash of it's content)
	Checksum []byte `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// The chunk's actual content
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// The offset of the chunk from the beginning of the file
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// The size of the chunk in bytes
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// The change version of the chunk. Used for contructing snapshots mid-session
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *InitialSyncChunk) Reset() {
	*x = InitialSyncChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialSyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSyncChunk) ProtoMessage() {}

func (x *InitialSyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSyncChunk.ProtoReflect.Descriptor instead.
func (*InitialSyncChunk) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *InitialSyncChunk) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *InitialSyncChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InitialSyncChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InitialSyncChunk) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitialSyncChunk) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ProjectSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files map[string]*InitialSyncFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // path -> file
}

func (x *ProjectSnapshot) Reset() {
	*x = ProjectSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_snapshot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSnapshot) ProtoMessage() {}

func (x *ProjectSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_snapshot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSnapshot.ProtoReflect.Descriptor instead.
func (*ProjectSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectSnapshot) GetFiles() map[string]*InitialSyncFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_snapshot_snapshot_proto protoreflect.FileDescriptor

var file_snapshot_snapshot_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x22, 0x8f, 0x02, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x46,
	0x0a, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x73, 0x79, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x2e, 0x45, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x48,
	0x00, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xdf, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65,
	0x6c, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x75, 0x6d, 0x12, 0x37, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52,
	0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x30, 0x0a, 0x14,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x12, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x37,
	0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x0b, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x7b, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x65, 0x77, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x6e, 0x65, 0x77, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x22, 0x10, 0x0a, 0x0e, 0x45,
	0x6e, 0x64, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x22, 0x5c, 0x0a,
	0x17, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e,
	0x63, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x61, 0x0a, 0x0f, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e,
	0x63, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x8e,
	0x01, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0xa2, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x3a, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a,
	0x53, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snapshot_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_snapshot_proto_rawDescData = file_snapshot_snapshot_proto_rawDesc
)

func file_snapshot_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_snapshot_snapshot_proto_rawDescData)
	})
	return file_snapshot_snapshot_proto_rawDescData
}

var file_snapshot_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_snapshot_snapshot_proto_goTypes = []interface{}{
	(*WebsocketMessage)(nil),        // 0: snapshot.WebsocketMessage
	(*FileDelta)(nil),               // 1: snapshot.FileDelta
	(*AddedChunk)(nil),              // 2: snapshot.AddedChunk
	(*MovedChunk)(nil),              // 3: snapshot.MovedChunk
	(*StartProjectSync)(nil),        // 4: snapshot.StartProjectSync
	(*EndProjectSync)(nil),          // 5: snapshot.EndProjectSync
	(*InitialSyncFileWithPath)(nil), // 6: snapshot.InitialSyncFileWithPath
	(*InitialSyncFile)(nil),         // 7: snapshot.InitialSyncFile
	(*InitialSyncChunk)(nil),        // 8: snapshot.InitialSyncChunk
	(*ProjectSnapshot)(nil),         // 9: snapshot.ProjectSnapshot
	nil,                             // 10: snapshot.ProjectSnapshot.FilesEntry
}
var file_snapshot_snapshot_proto_depIdxs = []int32{
	1,  // 0: snapshot.WebsocketMessage.file_delta:type_name -> snapshot.FileDelta
	6,  // 1: snapshot.WebsocketMessage.initial_file:type_name -> snapshot.InitialSyncFileWithPath
	4,  // 2: snapshot.WebsocketMessage.start_sync:type_name -> snapshot.StartProjectSync
	5,  // 3: snapshot.WebsocketMessage.end_sync:type_name -> snapshot.EndProjectSync
	2,  // 4: snapshot.FileDelta.added_chunks:type_name -> snapshot.AddedChunk
	3,  // 5: snapshot.FileDelta.moved_chunks:type_name -> snapshot.MovedChunk
	7,  // 6: snapshot.InitialSyncFileWithPath.file:type_name -> snapshot.InitialSyncFile
	8,  // 7: snapshot.InitialSyncFile.chunks:type_name -> snapshot.InitialSyncChunk
	10, // 8: snapshot.ProjectSnapshot.files:type_name -> snapshot.ProjectSnapshot.FilesEntry
	7,  // 9: snapshot.ProjectSnapshot.FilesEntry.value:type_name -> snapshot.InitialSyncFile
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_snapshot_snapshot_proto_init() }
func file_snapshot_snapshot_proto_init() {
	if File_snapshot_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snapshot_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsocketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovedChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProjectSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndProjectSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialSyncFileWithPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialSyncFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialSyncChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_snapshot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_snapshot_snapshot_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WebsocketMessage_FileDelta)(nil),
		(*WebsocketMessage_InitialFile)(nil),
		(*WebsocketMessage_StartSync)(nil),
		(*WebsocketMessage_EndSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snapshot_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_snapshot_proto = out.File
	file_snapshot_snapshot_proto_rawDesc = nil
	file_snapshot_snapshot_proto_goTypes = nil
	file_snapshot_snapshot_proto_depIdxs = nil
}
